### PR TITLE
Update to EFv2

### PR DESCRIPTION
**Pull request by johntwyman**
Upgrades the extension to use Entity Framework version 2. Tested in dev by loading the Models tab on a contact record.

### CODE REVIEW

**Comment by andrew-cormick-dockery** [comment]
There seems to be a bunch of permissions changes on the files erroneously?

**Comment by johntwyman** [comment]
> There seems to be a bunch of permissions changes on the files erroneously?

I'll revert them in a moment.

**Comment by andrew-cormick-dockery** [comment]
Come to think of it, are there actually any entities to upgrade here? Looks like a Civix upgrade to me...

**Comment by johntwyman** [comment]
> Come to think of it, are there actually any entities to upgrade here? Looks like a Civix upgrade to me...

`civix upgrade` is what's been done to convert the XML files to entityType files. `civix convert-entity` cannot be run until `civix upgrade` is run because of the changes to mixin versions, etc.

But `civix upgrade` itself asks if you want to convert to EFv2 as it runs anyway.

**Comment by johntwyman** [comment]
> > Come to think of it, are there actually any entities to upgrade here? Looks like a Civix upgrade to me...
> 
> `civix upgrade` is what's been done to convert the XML files to entityType files. `civix convert-entity` cannot be run until `civix upgrade` is run because of the changes to mixin versions, etc.
> 
> But `civix upgrade` itself asks if you want to convert to EFv2 as it runs anyway.

Additional note: it's the change in the mixins, etc., that's the big backwards breaking change, more than there being any entities to convert.

**Review by andrew-cormick-dockery — APPROVED** [review]

**Pull request merged**
